# Ansible inventory — generated by Terraform
# Template: inventory.tpl  |  DO NOT edit manually

# ---------------------------------------------------------------------------
# Linux web servers (Docker ubuntu-target)
# ---------------------------------------------------------------------------
[webservers]
%{ for idx, h in web_hosts ~}
${h} ansible_user=${ansible_user} ansible_connection=ssh ansible_ssh_private_key_file=${ansible_ssh_private_key} ansible_port=${ansible_ssh_port} server_id=${idx + 1}
%{ endfor ~}

# ---------------------------------------------------------------------------
# Load balancer
# ---------------------------------------------------------------------------
[loadbalancer]
${lb_host} ansible_user=${ansible_user} ansible_connection=local

# ---------------------------------------------------------------------------
# Windows VM (WinRM)
# ---------------------------------------------------------------------------
[windows]
${windows_host}

[windows:vars]
ansible_user=${windows_user}
ansible_password=${windows_password}
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_port=${winrm_port}
ansible_winrm_scheme=http
ansible_winrm_server_cert_validation=ignore

# ---------------------------------------------------------------------------
# Global
# ---------------------------------------------------------------------------
[all:vars]
ansible_python_interpreter=/usr/bin/python3
