# Ansible inventory — generated by Terraform
# Template: inventory.tpl
# Do NOT edit manually; re-run `terraform apply` to regenerate.

[webservers]
${host} ansible_user=${user} ansible_connection=${connection}

[all:vars]
ansible_python_interpreter=/usr/bin/python3
